channels:
  - defaults
  - conda-forge

dependencies:
  - jupyterlab=3.0
  - python=3.7.1
  - requests=2.26.0
  - pandas=1.3.2
  - matplotlib=3.4.2
  - seaborn=0.11.2
  - numpy=1.20.3
  - statsmodels=0.12.2
  - scikit-learn=0.24.2
  - scipy=1.7.1
  
